### ISSUE TITLE
Module export description in the tutorial does not work

### ISSUE THREAD

**Issue by mindv0rtex** [Wandalen/willbe#344]
If I follow this: https://github.com/Wandalen/willbe/blob/master/doc/version2.ukr/tutorial/ModuleExport.md
I get the following error:

```
Exporting module::exportModule / build::export.single
Expects glob path to export in export step. path::fileToExport is not glob
```

**Comment by dmvict** [comment]
Hello, @mindv0rtex.

Thank you for your help and this issue. We corrected the tutorial in [this PR](https://github.com/Wandalen/willbe/pull/346).
