### ISSUE TITLE
Bug in the criteria tutorial

### ISSUE THREAD

**Issue by mindv0rtex** [Wandalen/willbe#345]
Instructions in https://github.com/Wandalen/willbe/blob/master/doc/version2.ukr/tutorial/Criterions.md cause this error when I try to call `will .build echo.debug`:
```
 Building module::buildModuleWithCriterion / build::echo.debug
   = Message of Error#3
      Assertion fails
      Failed module::buildModuleWithCriterion / step::echo.output
```
followed by a long call stack.

**Comment by dmvict** [comment]
Hello, @mindv0rtex.

Thank you for your help and this issue. We corrected the tutorial in [this PR](https://github.com/Wandalen/willbe/pull/346).

**Comment by mindv0rtex** [comment]
Great!
